name: C CI

on:
  push:
    branches: [ "main", "ultimate-chaaaaaaanges" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    #- name: configure
    #  run: ./configure
    -  run: make
    -  run: make test
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
  test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: blank-test
        run: make test
      - name: mpanic
        run: make panic
