name: C CI

on: [push, pull_request]

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
      with:
        flags: '.'
  norme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install norminette
      run: bash .github/norme-install.sh
    - name: run test
      run: norminette.sh
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make
    - name: blank test
      run: make test
    - name: mpanic test
      run: make panic
