name: Minishell CI

on: [push, pull_request]

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
      with:
        flags: '.'
  blank-tests-1-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make
    - name: test
      run: make test
  blank-tests-2-2:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make
    - name: test
      run: make test
  mpanic-tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make FORCE_PROMPT=1
    - name: test
      run: make FORCE_PROMPT=1 mpanic
