name: Minishell CI

on: [push, pull_request]

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
      with:
        flags: '.'
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make
    - name: test
      run: make test
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make
    - name: amethyst-test
      run: bash tests/test2.sh
    - name: blank-test
      run: make test
    - name: build FORCE_PROMPT
      run: make FORCE_PROMPT=1
    - name: mpanic-test
      run: make FORCE_PROMPT=1 mpanic
