name: Makefile CI

on:
  push:
    branches: [ "main", "testing" ]
  pull_request:
    branches: [ "main" , "testing"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make
    - name: test
      run: make
